# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3finder < Formula
  desc "AI-powered S3 bucket enumeration tool"
  homepage "https://github.com/xeloxa/s3finder"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xeloxa/s3finder/releases/download/v1.0.3/s3finder_1.0.3_darwin_amd64.tar.gz"
      sha256 "84e423eb9d9c72cdc3819d47a470f8379777df9e9323adf8fee047aae8a5e96d"

      def install
        bin.install "s3finder"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xeloxa/s3finder/releases/download/v1.0.3/s3finder_1.0.3_darwin_arm64.tar.gz"
      sha256 "3ad7d2f0a9139360b973957786f85401294b79ef529613e6982541492d13807e"

      def install
        bin.install "s3finder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xeloxa/s3finder/releases/download/v1.0.3/s3finder_1.0.3_linux_amd64.tar.gz"
      sha256 "454bf6a93c47c3b94769574d07f1f5be03e125eebff4cb3954472f2507eef596"
      def install
        bin.install "s3finder"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xeloxa/s3finder/releases/download/v1.0.3/s3finder_1.0.3_linux_arm64.tar.gz"
      sha256 "b825b748fe4b143de635b88638f628e09bb25e5dea4ada7c3dce55fe9f53a041"
      def install
        bin.install "s3finder"
      end
    end
  end
end
