# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3finder < Formula
  desc "AI-powered S3 bucket enumeration tool"
  homepage "https://github.com/xeloxa/s3finder"
  version "1.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xeloxa/s3finder/releases/download/v1.2.2/s3finder_1.2.2_darwin_amd64.tar.gz"
      sha256 "4ba28c391e031dcb59bac1f0658074466de2b7f10418f83e1f75de7549514267"

      def install
        bin.install "s3finder"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xeloxa/s3finder/releases/download/v1.2.2/s3finder_1.2.2_darwin_arm64.tar.gz"
      sha256 "0ea4b00128f1cbb9cae3f08adc51e3954f9557710026674547d3458b4bfbb519"

      def install
        bin.install "s3finder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xeloxa/s3finder/releases/download/v1.2.2/s3finder_1.2.2_linux_amd64.tar.gz"
      sha256 "9332fe3548fa3b93952d6d8a2303d05a00d567c2b5a316f367ccb7e8bf4aa2f8"
      def install
        bin.install "s3finder"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xeloxa/s3finder/releases/download/v1.2.2/s3finder_1.2.2_linux_arm64.tar.gz"
      sha256 "dac324e383b2b5175dee5b22b8106e951d0ff68e3779ccb0e7da41d8d587e051"
      def install
        bin.install "s3finder"
      end
    end
  end
end
