# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class S3finder < Formula
  desc "AI-powered S3 bucket enumeration tool"
  homepage "https://github.com/xeloxa/s3finder"
  version "1.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xeloxa/s3finder/releases/download/v1.2.4/s3finder_1.2.4_darwin_amd64.tar.gz"
      sha256 "485646861f9742fdf0aa7456541c907cf2922d6101ef3a26a0fcd0ee845bbf18"

      def install
        bin.install "s3finder"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xeloxa/s3finder/releases/download/v1.2.4/s3finder_1.2.4_darwin_arm64.tar.gz"
      sha256 "ef2317b3e47f2ac5d901bbea137149cc3e16f0fddb8e0d8ffbd686ac4a2e2788"

      def install
        bin.install "s3finder"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xeloxa/s3finder/releases/download/v1.2.4/s3finder_1.2.4_linux_amd64.tar.gz"
      sha256 "5237b5937a15227f153d9f86f02645a71dcfbff540f03d0013493916a90999bd"
      def install
        bin.install "s3finder"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xeloxa/s3finder/releases/download/v1.2.4/s3finder_1.2.4_linux_arm64.tar.gz"
      sha256 "7f2f36af9083017cf2b913c29c964bd444c96732bfe4080e6d741c8d9b795d81"
      def install
        bin.install "s3finder"
      end
    end
  end
end
